apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "config.yml"
  - "deployment.yml"
  - "ingress.yml"
  - "namespace.yml"
  - "service.yml"

images:
  - name: digitalphoenixx/expense-tracker-api:latest
    newName: digitalphoenixx/expense-tracker-api
    newTag: latest
